# Generated by Django 3.2.5 on 2021-08-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernm', models.CharField(max_length=50)),
                ('signupdt', models.DateTimeField()),
                ('u_segmt', models.CharField(max_length=5)),
            ],
        ),
    ]
